name: anystep
description: "A mobile volunteer tracking app for AnyStep."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  app_links: ^6.3.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dart_geohash: ^2.1.0
  dio: ^5.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_remote_config: ^6.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^10.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.1.2
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mime: ^2.0.0
  posthog_flutter: ^5.6.0
  riverpod_annotation: ^3.0.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2
  vector_math: ^2.2.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoSlab/RobotoSlab-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab/RobotoSlab-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Black.ttf
          weight: 900
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
