name: anystep
description: "A mobile volunteer tracking app for AnyStep."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dart_geohash: ^2.1.0
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^10.0.1
  flutter_riverpod: ^2.3.2
  form_builder_validators: ^11.1.2
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mime: ^2.0.0
  posthog_flutter: ^5.6.0
  riverpod_annotation: ^2.0.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
